# Generated by Django 3.2.12 on 2024-04-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='shop.categoria'),
        ),
        migrations.AlterField(
            model_name='producte',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.Tag'),
        ),
    ]
